salesforce:
 username: "![qJZ6HjZtiC0dpYxmQyJiptOFDxdgDPUIoS0dmu7d6q4=]"
 password: "![fQrjowPakZHekUK9xaW3fA==]"
 securitytoken: "![KttTugD6Rxthm1JYjOoB6r7P02DbwzovbOc2iP2YMdM=]"


 
https:
 port: "8082"
 
autodiscovery:
 id: "19054012"
 
enableConsole: "true"

tls:
 password: "![GtWPXnfCuh8Coxj4kZvHfg==]"
 keypassword: "![GtWPXnfCuh8Coxj4kZvHfg==]"
 
key: "password12345678"