#%RAML 1.0 Library

types:
  Contact:
    properties:
      Id: string
      Email: string
      FirstName: string
      MailingCountry: string
      Title: string
      MailingCity: string
      type: string
      OtherState: string
      OtherStreet: string
      MailingState: string
      MobilePhone: string
      OtherCity: string
      MailingPostalCode: string
      OtherCountry: string
      LastName: string
      MailingStreet: string
      ExternalId__c: 
        type: integer
        required: false
      SyncNewRecordToDb__c: 
        type: string
        required: false
      SyncUpdatedRecordToDb__c: 
        type: string
        required: false

  contactArray:
    type: array
    items: Contact
